services:
  server1:
    build: server
    tty: true
    command: -p 8082
  gateway:
    build: gateway
    tty: true
    command: -p 8000 -i 10 --sync_interval 15 -s server1:8082
  client1: &client
    build: client
    tty: true
    depends_on:
      - gateway
    command: -a gateway -p 8000 -d 1 -m 60 -i 2 --id 1
  client2:
    <<: *client
    command: -a gateway -p 8000 -d 1 -m 60 -i 2 --id 2